config/routes.rb
Rails.application.routes.draw do
  root 'mains#index'
  resources :users
  resources :roles
  resources :roles_names
  resources :mains
  resources :db_connections
  resources :applications
  resources :important_conf_files
  resources :partitionings
  resources :server_group_infos
  resources :server_states
  resources :os_infos
  resources :machine_types
  resources :site_names
  resources :ip_histories
  resources :server_main_infos do
    get 'treeview', on: :collection
    get 'treeview_item', on: :member
  end
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :server_main_info
  has_many :db_connections

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/db_connection.rb
class DbConnection < ApplicationRecord
  belongs_to :application
end

app/models/ip_history.rb
class IpHistory < ApplicationRecord
  belongs_to :server_main_info

end

app/models/machine_type.rb
class MachineType < ApplicationRecord
  has_many :server_main_infos

end

app/models/os_info.rb
class OsInfo < ApplicationRecord
  has_many :server_main_infos

end

app/models/partitioning.rb
class Partitioning < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/roles_name.rb
class RolesName < ApplicationRecord
end

app/models/server_group_info.rb
class ServerGroupInfo < ApplicationRecord
  has_many :server_main_info

end

app/models/server_main_info.rb
require 'resolv'
class ServerMainInfo < ApplicationRecord
  belongs_to :os_info
  belongs_to :machine_type
  belongs_to :site_name
  belongs_to :server_state
  belongs_to :os_info
  has_many :ip_histories
  has_many :server_group_infos
  has_many :applications

  validates :srvName, :mainIP, :srvNameInProj, :srvPersianName, :sitename_id, :osinfo_id, :machinetype_id, :serverstate_id, :subnetMask, :gateWay,
            :projName, :responseName, :reponseUnit_id, :responseOrg_id, :responsePhone, presence: true
  validates :mainIP, :ip1, :ip2, :ip3, :validIP, :gateWay, format: { with: Resolv::IPv4::Regex , message: "آدرس شبکه ای دارای قالب درست نمی باشد" }
  validates :macAddr, :mac_1, :mac_2, :mac_3, format: { with: /\A([0-9a-fA-F]{2}:{1}){5}([0-9a-fA-F]{2}){1}\z/i , message: "قالب آدرس کارت شبکه صحیح نمی باشد"}
  validates :responseMail, format: { with: URI::MailTo::EMAIL_REGEXP, message: "قالب آدرس پست الکترونیکی صحیح نمی باشد"}
  validates :subnetMask, numericality: { only_integer: true, less_than_or_equal_to: 32 , greater_than_or_equal_to: 0}
  validates :fdqn, :validFqdn, format: { with: /\A\w+\.\w+\.\w\z/i , message: "لطفا نام شبکه ای را بطور صحیح وارد نمایید"}


end

app/models/server_state.rb
class ServerState < ApplicationRecord
  has_many :server_main_infos

end

app/models/site_name.rb
class SiteName < ApplicationRecord
  has_many :server_main_infos

end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1 or /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:appName, :appTpe, :developer, :version, :serviceName, :appUrl, :contextRoot, :dbconnection_id, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/os_infos_helper.rb
module OsInfosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/site_names_helper.rb
module SiteNamesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :appName %>
    <%= form.text_field :appName %>
  </div>

  <div class="field">
    <%= form.label :appTpe %>
    <%= form.text_field :appTpe %>
  </div>

  <div class="field">
    <%= form.label :developer %>
    <%= form.text_field :developer %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :serviceName %>
    <%= form.text_field :serviceName %>
  </div>

  <div class="field">
    <%= form.label :appUrl %>
    <%= form.text_field :appUrl %>
  </div>

  <div class="field">
    <%= form.label :contextRoot %>
    <%= form.text_field :contextRoot %>
  </div>

  <div class="field">
    <%= form.label :dbconnection_id %>
    <%= form.number_field :dbconnection_id %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t :wApplications %></h1>

<table>
  <thead>
    <tr>
      <th><%= t :'activerecord.attributes.application.appName' %></th>
      <th><%= t :'activerecord.attributes.application.appType' %></th>
      <th><%= t :'activerecord.attributes.application.developer' %></th>
      <th><%= t :'activerecord.attributes.application.version' %></th>
      <th><%= t 'activerecord.attributes.application.serviceName' %></th>
      <th><%= t 'activerecord.attributes.application.appUrl' %></th>
      <th><%= t 'activerecord.attributes.application.contextRoot' %></th>
      <th><%= t 'activerecord.attributes.application.dbconnection' %></th>
      <th><%= t 'activerecord.attributes.application.note' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.appName %></td>
        <td><%= application.appType %></td>
        <td><%= application.developer %></td>
        <td><%= application.version %></td>
        <td><%= application.serviceName %></td>
        <td><%= application.appUrl %></td>
        <td><%= application.contextRoot %></td>
        <td><%= application.dbconnection_id %></td>
        <td><%= application.note %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appname:</strong>
  <%= @application.appName %>
</p>

<p>
  <strong>Apptpe:</strong>
  <%= @application.appTpe %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @application.developer %>
</p>

<p>
  <strong>Version:</strong>
  <%= @application.version %>
</p>

<p>
  <strong>Servicename:</strong>
  <%= @application.serviceName %>
</p>

<p>
  <strong>Appurl:</strong>
  <%= @application.appUrl %>
</p>

<p>
  <strong>Contextroot:</strong>
  <%= @application.contextRoot %>
</p>

<p>
  <strong>Dbconnection:</strong>
  <%= @application.dbconnection_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @application.note %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>