config/routes.rb
Rails.application.routes.draw do
  root 'mains#index'
  resources :users
  resources :roles
  resources :roles_names
  resources :mains
  resources :db_connections
  resources :applications
  resources :important_conf_files
  resources :partitionings
  resources :server_group_infos
  resources :server_states
  resources :os_infos
  resources :machine_types
  resources :site_names
  resources :ip_histories
  resources :server_main_infos do
    get 'treeview', on: :collection
    get 'treeview_item', on: :member
  end
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :server_main_info
  has_many :db_connections

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/db_connection.rb
class DbConnection < ApplicationRecord
  belongs_to :application
end

app/models/ip_history.rb
class IpHistory < ApplicationRecord
  belongs_to :server_main_info

end

app/models/machine_type.rb
class MachineType < ApplicationRecord
  has_many :server_main_infos

end

app/models/os_info.rb
class OsInfo < ApplicationRecord
  has_many :server_main_infos

end

app/models/partitioning.rb
class Partitioning < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/roles_name.rb
class RolesName < ApplicationRecord
end

app/models/server_group_info.rb
class ServerGroupInfo < ApplicationRecord
  has_many :server_main_info

end

app/models/server_main_info.rb
require 'resolv'
class ServerMainInfo < ApplicationRecord
  belongs_to :os_info
  belongs_to :machine_type
  belongs_to :site_name
  belongs_to :server_state
  belongs_to :os_info
  has_many :ip_histories
  has_many :server_group_infos
  has_many :applications

  validates :srvName, :mainIP, :srvNameInProj, :srvPersianName, :sitename_id, :osinfo_id, :machinetype_id, :serverstate_id, :subnetMask, :gateWay,
            :projName, :responseName, :reponseUnit_id, :responseOrg_id, :responsePhone, presence: true
  validates :mainIP, :ip1, :ip2, :ip3, :validIP, :gateWay, format: { with: Resolv::IPv4::Regex , message: "آدرس شبکه ای دارای قالب درست نمی باشد" }
  validates :macAddr, :mac_1, :mac_2, :mac_3, format: { with: /\A([0-9a-fA-F]{2}:{1}){5}([0-9a-fA-F]{2}){1}\z/i , message: "قالب آدرس کارت شبکه صحیح نمی باشد"}
  validates :responseMail, format: { with: URI::MailTo::EMAIL_REGEXP, message: "قالب آدرس پست الکترونیکی صحیح نمی باشد"}
  validates :subnetMask, numericality: { only_integer: true, less_than_or_equal_to: 32 , greater_than_or_equal_to: 0}
  validates :fdqn, :validFqdn, format: { with: /\A\w+\.\w+\.\w\z/i , message: "لطفا نام شبکه ای را بطور صحیح وارد نمایید"}


end

app/models/server_state.rb
class ServerState < ApplicationRecord
  has_many :server_main_infos

end

app/models/site_name.rb
class SiteName < ApplicationRecord
  has_many :server_main_infos

end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/server_main_infos_controller.rb
class ServerMainInfosController < ApplicationController
  before_action :set_server_main_info, only: %i[ show edit update destroy ]

  # GET /server_main_infos or /server_main_infos.json
  $server_main_infos = ServerMainInfo.all
  def index
  end

  # GET /server_main_infos/1 or /server_main_infos/1.json
  def show
  end

  # TreeView Action
  def treeview
  end

  def treeview_item
    # paginates_per 5
    @servergroupinfo_all_pagination = ServerGroupInfo.order(:grpName).page(params[:page]).per(5)
    @treeviewItem= ServerMainInfo.find(params[:id])
    respond_to do |format|
      format.js { render layout: false }
    end

  end
  # GET /server_main_infos/new
  def new
    @server_main_info = ServerMainInfo.new
    # paginates_per 5
    @servergroupinfo_all_pagination = ServerGroupInfo.order(:grpName).page(params[:page]).per(5)
  end

  # GET /server_main_infos/1/edit
  def edit
    # paginates_per 5
    @servergroupinfo_all_pagination = ServerGroupInfo.order(:grpName).page(params[:page]).per(5)
  end

  # POST /server_main_infos or /server_main_infos.json
  def create
    @server_main_info = ServerMainInfo.new(server_main_info_params)

    respond_to do |format|
      if @server_main_info.save
        format.html { redirect_to @server_main_info, notice: "Server main info was successfully created." }
        format.json { render :show, status: :created, location: @server_main_info }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @server_main_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /server_main_infos/1 or /server_main_infos/1.json
  def update
    # paginates_per 5
    @servergroupinfo_all_pagination = ServerGroupInfo.order(:grpName).page(params[:page]).per(5)
    respond_to do |format|
      if @server_main_info.update(server_main_info_params)
        format.html { redirect_to @server_main_info, notice: "Server main info was successfully updated." }
        format.json { render :show, status: :ok, location: @server_main_info }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @server_main_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_main_infos/1 or /server_main_infos/1.json
  def destroy
    @server_main_info.destroy
    respond_to do |format|
      format.html { redirect_to server_main_infos_url, notice: "Server main info was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server_main_info
      @server_main_info = ServerMainInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def server_main_info_params
      params.require(:server_main_info).permit(:srvName, :fdqn, :mainIP, :iphistory_id, :macAddr, :ip1, :ip2, :ip3, :mac_1, :mac_2, :mac_3, :srvNameInProj, :srvPersianName, :sitename_id, :osinfo_id, :srvNameOnVM, :machinetype_id, :serverstate_id, :cpuInfo, :ramInfo, :hddInfo, :validIP, :validFqdn, :subnetMask, :gateWay, :projName, :reponseUnit_id, :responseOrg_id, :responseName, :responsePhone, :responseMail)
    end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/os_infos_helper.rb
module OsInfosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/server_main_infos_helper.rb
module ServerMainInfosHelper
end

app/helpers/site_names_helper.rb
module SiteNamesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/server_main_infos/_form.html.erb
<%= form_with(model: server_main_info) do |form| %>
  <% if server_main_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server_main_info.errors.count, "error") %> prohibited this server_main_info from being saved:</h2>

      <ul>
        <% server_main_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :srvName %>
    <%= form.text_field :srvName %>
  </div>

  <div class="field">
    <%= form.label :fdqn %>
    <%= form.text_field :fdqn %>
  </div>

  <div class="container-fluid">
    <%= form.label :servergroupinfo_id %>
    <div class="container pagination">
      <%= form.collection_select :servergroupinfo_id  , @servergroupinfo_all_pagination ,:id, :grpName, class: "dropdown pagination", :selected => params[:servergroupinfo_id] %>
      <%= paginate @servergroupinfo_all_pagination , class: "page-item page-link" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :mainIP %>
    <%= form.text_field :mainIP %>
  </div>

  <div class="field">
    <%= form.label :iphistory_id %>
    <%= form.number_field :iphistory_id %>
  </div>

  <div class="field">
    <%= form.label :macAddr %>
    <%= form.text_field :macAddr %>
  </div>

  <div class="field">
    <%= form.label :ip1 %>
    <%= form.text_field :ip1 %>
  </div>

  <div class="field">
    <%= form.label :ip2 %>
    <%= form.text_field :ip2 %>
  </div>

  <div class="field">
    <%= form.label :ip3 %>
    <%= form.text_field :ip3 %>
  </div>

  <div class="field">
    <%= form.label :mac_1 %>
    <%= form.text_field :mac_1 %>
  </div>

  <div class="field">
    <%= form.label :mac_2 %>
    <%= form.text_field :mac_2 %>
  </div>

  <div class="field">
    <%= form.label :mac_3 %>
    <%= form.text_field :mac_3 %>
  </div>

  <div class="field">
    <%= form.label :srvNameInProj %>
    <%= form.text_field :srvNameInProj %>
  </div>

  <div class="field">
    <%= form.label :srvPersianName %>
    <%= form.text_field :srvPersianName %>
  </div>

  <div class="field">
    <%= form.label :sitename_id %>
    <%= form.collection_select :sitename_id, SiteName.all,:id,:siteName, :selected => params[:sitename_id] %>
  </div>

  <div class="field">
    <%= form.label :osinfo_id %>
    <%= form.collection_select :osinfo_id, OsInfo.all,:id, :osName, :selected => params[:osInfo_id] %>
  </div>

  <div class="field">
    <%= form.label :srvNameOnVM %>
    <%= form.text_field :srvNameOnVM %>
  </div>

  <div class="field">
    <%= form.label :machinetype_id %>
    <%= form.collection_select :machinetype_id, MachineType.all, :id, :machineType, :selected => params[:machinetype_id] %>
  </div>

  <div class="field">
    <%= form.label :serverstate_id %>
    <%= form.collection_select :serverstate_id , ServerState.all,:id, :srvState, :selected => params[:serverstate_id]%>
  </div>

  <div class="field">
    <%= form.label :cpuInfo %>
    <%= form.text_field :cpuInfo %>
  </div>

  <div class="field">
    <%= form.label :ramInfo %>
    <%= form.text_field :ramInfo %>
  </div>

  <div class="field">
    <%= form.label :hddInfo %>
    <%= form.text_field :hddInfo %>
  </div>

  <div class="field">
    <%= form.label :validIP %>
    <%= form.text_field :validIP %>
  </div>

  <div class="field">
    <%= form.label :validFqdn %>
    <%= form.text_field :validFqdn %>
  </div>

  <div class="field">
    <%= form.label :subnetMask %>
    <%= form.text_field :subnetMask %>
  </div>

  <div class="field">
    <%= form.label :gateWay %>
    <%= form.text_field :gateWay %>
  </div>

  <div class="field">
    <%= form.label :projName %>
    <%= form.text_field :projName %>
  </div>

  <div class="field">
    <%= form.label :reponseUnit_id %>
    <%= form.number_field :reponseUnit_id %>
  </div>

  <div class="field">
    <%= form.label :responseOrg_id %>
    <%= form.number_field :responseOrg_id %>
  </div>

  <div class="field">
    <%= form.label :responseName %>
    <%= form.text_field :responseName %>
  </div>

  <div class="field">
    <%= form.label :responsePhone %>
    <%= form.text_field :responsePhone %>
  </div>

  <div class="field">
    <%= form.label :responseMail %>
    <%= form.text_field :responseMail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/server_main_infos/_treeview.html.erb
<%= form_with(model: server_main_info) do |form| %>
  <% if server_main_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server_main_info.errors.count, "error") %> prohibited this server_main_info from being saved:</h2>

      <ul>
        <% server_main_info.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :srvName %>
    <%= form.text_field :srvName %>
  </div>

  <div class="field">
    <%= form.label :fdqn %>
    <%= form.text_field :fdqn %>
  </div>

  <div class="field">
    <%= form.label :servergroupinfo_id %>
    <div class="container pagination">
      <%= form.collection_select :servergroupinfo_id  , @servergroupinfo_all_pagination,:id, :grpName, class: "dropdown pagination", :selected => params[:servergroupinfo_id] %>
      <%= paginate @servergroupinfo_all_pagination , class: "page-item page-link" %>
    </div>
  </div>
  <div class="field">
    <%= form.label :sitename_id %>
    <%= form.collection_select :sitename_id, SiteName.all,:id,:siteName, :selected => params[:sitename_id] %>
  </div>

  <div class="field">
    <%= form.label :mainIP %>
    <%= form.text_field :mainIP %>
  </div>

  <div class="field">
    <%= form.label :iphistory_id %>
    <%= form.number_field :iphistory_id %>
  </div>

  <div class="field">
    <%= form.label :macAddr %>
    <%= form.text_field :macAddr %>
  </div>

  <div class="field">
    <%= form.label :ip1 %>
    <%= form.text_field :ip1 %>
  </div>

  <div class="field">
    <%= form.label :ip2 %>
    <%= form.text_field :ip2 %>
  </div>

  <div class="field">
    <%= form.label :ip3 %>
    <%= form.text_field :ip3 %>
  </div>

  <div class="field">
    <%= form.label :mac_1 %>
    <%= form.text_field :mac_1 %>
  </div>

  <div class="field">
    <%= form.label :mac_2 %>
    <%= form.text_field :mac_2 %>
  </div>

  <div class="field">
    <%= form.label :mac_3 %>
    <%= form.text_field :mac_3 %>
  </div>

  <div class="field">
    <%= form.label :srvNameInProj %>
    <%= form.text_field :srvNameInProj %>
  </div>

  <div class="field">
    <%= form.label :srvPersianName %>
    <%= form.text_field :srvPersianName %>
  </div>

  <div class="field">
    <%= form.label :sitename_id %>
    <%= form.collection_select :sitename_id, SiteName.all,:id,:siteName, :selected => params[:sitename_id] %>
  </div>

  <div class="field">
    <%= form.label :osinfo_id %>
    <%= form.collection_select :osinfo_id, OsInfo.all,:id, :osName, :selected => params[:osInfo_id] %>
  </div>

  <div class="field">
    <%= form.label :srvNameOnVM %>
    <%= form.text_field :srvNameOnVM %>
  </div>

  <div class="field">
    <%= form.label :machinetype_id %>
    <%= form.collection_select :machinetype_id, MachineType.all, :id, :machineType, :selected => params[:machinetype_id] %>
  </div>

  <div class="field">
    <%= form.label :serverstate_id %>
    <%= form.collection_select :serverstate_id , ServerState.all,:id, :srvState, :selected => params[:serverstate_id] %>
  </div>

  <div class="field">
    <%= form.label :cpuInfo %>
    <%= form.text_field :cpuInfo %>
  </div>

  <div class="field">
    <%= form.label :ramInfo %>
    <%= form.text_field :ramInfo %>
  </div>

  <div class="field">
    <%= form.label :hddInfo %>
    <%= form.text_field :hddInfo %>
  </div>

  <div class="field">
    <%= form.label :validIP %>
    <%= form.text_field :validIP %>
  </div>

  <div class="field">
    <%= form.label :validFqdn %>
    <%= form.text_field :validFqdn %>
  </div>

  <div class="field">
    <%= form.label :subnetMask %>
    <%= form.text_field :subnetMask %>
  </div>

  <div class="field">
    <%= form.label :gateWay %>
    <%= form.text_field :gateWay %>
  </div>

  <div class="field">
    <%= form.label :projName %>
    <%= form.text_field :projName %>
  </div>

  <div class="field">
    <%= form.label :reponseUnit_id %>
    <%= form.number_field :reponseUnit_id %>
  </div>

  <div class="field">
    <%= form.label :responseOrg_id %>
    <%= form.number_field :responseOrg_id %>
  </div>

  <div class="field">
    <%= form.label :responseName %>
    <%= form.text_field :responseName %>
  </div>

  <div class="field">
    <%= form.label :responsePhone %>
    <%= form.text_field :responsePhone %>
  </div>

  <div class="field">
    <%= form.label :responseMail %>
    <%= form.text_field :responseMail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/server_main_infos/edit.html.erb
<h1>Editing Server Main Info</h1>

<%= render 'form', server_main_info: @server_main_info %>

<%= link_to 'Show', @server_main_info %> |
<%= link_to 'Back', server_main_infos_path %>

app/views/server_main_infos/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t :wServerStateTitle %></h1>

<div class="container bg-info">
  <h3><%= t :'activerecord.models.server_main_info' %></h3>
  <table>
    <thead>
      <tr>
        <th><%= t :'activerecord.attributes.server_main_info.srvName' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.fdqn' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.mainIP' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.macAddr' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.validIP' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.validFqdn' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.subnetMask' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.gateWay' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.projName' %></th>
        <th colspan="3"> </th>
      </tr>
    </thead>
    <tbody>
      <% @server_main_infos.each do |server_main_info| %>
        <tr>
          <td><%= server_main_info.srvname %></td>
          <td><%= server_main_info.fdqn %></td>
          <td><%= server_main_info.mainip %></td>
          <td><%= server_main_info.macaddr %></td>
          <td><%= server_main_info.validip %></td>
          <td><%= server_main_info.validfqdn %></td>
          <td><%= server_main_info.subnetmask %></td>
          <td><%= server_main_info.gateway %></td>
          <td><%= server_main_info.projname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container bg-success">
  <h3><%= t :wProjInfo %></h3>
  <table>
    <thead>
    <tr>
      <th><%= t :'activerecord.attributes.server_main_info.srvNameInProj' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.srvPersianName' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.srvNameOnVM' %></th>
      <th> SiteName</th>
      <th>OS Info</th>
      <th>machineType </th>
      <th>serverState </th>
      <th><%= t :'activerecord.attributes.server_main_info.responseUnit' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.responseOrg' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.responseName' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.responsePhone' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.responseMail' %></th>
    </tr>
    </thead>
    <tbody>
      <% @server_main_infos.each do |server_main_info| %>
        <td><%= server_main_info.srvnameinproj %></td>
        <td><%= server_main_info.srvpersianname %></td>
        <td><%= server_main_info.srvnameonvm %></td>
        <td><%= server_main_info.sitename_id %></td>
        <td><%= server_main_info.osinfo_id %></td>
        <td><%= server_main_info.machinetype_id %></td>
        <td><%= server_main_info.serverstate_id %></td>
        <td><%= server_main_info.reponseunit_id %></td>
        <td><%= server_main_info.responseorg_id %></td>
        <td><%= server_main_info.responsename %></td>
        <td><%= server_main_info.responsephone %></td>
        <td><%= server_main_info.responsemail %></td>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container bg-warning">
  <h3><%= t :wResourceInfo %></h3>
  <table>
    <thead>
      <tr>
        <th><%= t :'activerecord.attributes.server_main_info.cpuInfo' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.ramInfo' %></th>
        <th><%= t :'activerecord.attributes.server_main_info.hddInfo' %></th>
      </tr>
    </thead>
    <tbody>
      <% @server_main_infos.each do |server_main_info|%>
        <tr>
          <td><%= server_main_info.cpuinfo %></td>
          <td><%= server_main_info.raminfo %></td>
          <td><%= server_main_info.hddinfo %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container">
  <h3><%= t :wIPHistoryTitle %></h3>
  <table>
    <thead>
    <tr>
      <th><%= t :'activerecord.attributes.server_main_info.ip1' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.ip2' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.ip3' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.mac_1' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.mac_2' %></th>
      <th><%= t :'activerecord.attributes.server_main_info.mac_3' %></th>

    </tr>
    </thead>
    <tbody>
      <% @server_main_infos.each do |server_main_info| %>
        <tr>
          <td><%= server_main_info.ip1 %></td>
          <td><%= server_main_info.ip2 %></td>
          <td><%= server_main_info.ip3 %></td>
          <td><%= server_main_info.mac_1 %></td>
          <td><%= server_main_info.mac_2 %></td>
          <td><%= server_main_info.mac_3 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <h5><%= t :wIPHistoryTitle %></h5>
    <th> IPHistory </th>
  </div>
</div>
<div class="container">
  <table>
    <thead>
    <tr>
      <th colspan="3"> </th>
    </tr>
    </thead>

    <tbody>
    <% @server_main_infos.each do |server_main_info| %>
      <tr>
        <td><%= link_to 'show', server_main_info %></td>
        <td><%= link_to 'edit', edit_server_main_info_path(server_main_info) %></td>
        <td><%= link_to 'destroy', server_main_info, method: :delete, data: { confirm: 'are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

<br>

<%= link_to 'new server main info', new_server_main_info_path %>

app/views/server_main_infos/new.html.erb
<h1>New Server Main Info</h1>

<%= render 'form', server_main_info: @server_main_info %>

<%= link_to 'Back', server_main_infos_path %>

app/views/server_main_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Srvname:</strong>
  <%= @server_main_info.srvName %>
</p>

<p>
  <strong>Fdqn:</strong>
  <%= @server_main_info.fdqn %>
</p>

<p>
  <strong>Mainip:</strong>
  <%= @server_main_info.mainIP %>
</p>

<p>
  <strong>Iphistory:</strong>
  <%= @server_main_info.iphistory_id %>
</p>

<p>
  <strong>Macaddr:</strong>
  <%= @server_main_info.macAddr %>
</p>

<p>
  <strong>Ip1:</strong>
  <%= @server_main_info.ip1 %>
</p>

<p>
  <strong>Ip2:</strong>
  <%= @server_main_info.ip2 %>
</p>

<p>
  <strong>Ip3:</strong>
  <%= @server_main_info.ip3 %>
</p>

<p>
  <strong>Mac 1:</strong>
  <%= @server_main_info.mac_1 %>
</p>

<p>
  <strong>Mac 2:</strong>
  <%= @server_main_info.mac_2 %>
</p>

<p>
  <strong>Mac 3:</strong>
  <%= @server_main_info.mac_3 %>
</p>

<p>
  <strong>Srvnameinproj:</strong>
  <%= @server_main_info.srvNameInProj %>
</p>

<p>
  <strong>Srvpersianname:</strong>
  <%= @server_main_info.srvPersianName %>
</p>

<p>
  <strong>Sitename:</strong>
  <%= @server_main_info.sitename_id %>
</p>

<p>
  <strong>Osinfo:</strong>
  <%= @server_main_info.osinfo_id %>
</p>

<p>
  <strong>Srvnameonvm:</strong>
  <%= @server_main_info.srvNameOnVM %>
</p>

<p>
  <strong>Machinetype:</strong>
  <%= @server_main_info.machinetype_id %>
</p>

<p>
  <strong>Serverstate:</strong>
  <%= @server_main_info.serverstate_id %>
</p>

<p>
  <strong>Cpuinfo:</strong>
  <%= @server_main_info.cpuInfo %>
</p>

<p>
  <strong>Raminfo:</strong>
  <%= @server_main_info.ramInfo %>
</p>

<p>
  <strong>Hddinfo:</strong>
  <%= @server_main_info.hddInfo %>
</p>

<p>
  <strong>Validip:</strong>
  <%= @server_main_info.validIP %>
</p>

<p>
  <strong>Validfqdn:</strong>
  <%= @server_main_info.validFqdn %>
</p>

<p>
  <strong>Subnetmask:</strong>
  <%= @server_main_info.subnetMask %>
</p>

<p>
  <strong>Gateway:</strong>
  <%= @server_main_info.gateWay %>
</p>

<p>
  <strong>Projname:</strong>
  <%= @server_main_info.projName %>
</p>

<p>
  <strong>Reponseunit:</strong>
  <%= @server_main_info.reponseUnit_id %>
</p>

<p>
  <strong>Responseorg:</strong>
  <%= @server_main_info.responseOrg_id %>
</p>

<p>
  <strong>Responsename:</strong>
  <%= @server_main_info.responseName %>
</p>

<p>
  <strong>Responsephone:</strong>
  <%= @server_main_info.responsePhone %>
</p>

<p>
  <strong>Responsemail:</strong>
  <%= @server_main_info.responseMail %>
</p>

<%= link_to 'Edit', edit_server_main_info_path(@server_main_info) %> |
<%= link_to 'Back', server_main_infos_path %>

app/views/server_main_infos/treeview.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t :wServerStateTitle %></h1>

<h3><%= t :'activerecord.models.server_main_info' %></h3>
<div class="container-fluid ">
  <div class="row flex-nowrap">
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <div class="overflow-scroll">
          <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
              <% $server_main_infos.each do |server_main_info| %>
                <%= link_to treeview_item_server_main_info_path(server_main_info), class:"nav-link align-middle px-0", remote: true do %>
                  <em class="fs-4 bi-server"></em> <span class="ms-1 d-none d-sm-inline"><%= server_main_info.srvName %></span>
                <% end %>
              <% end %>>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col py-3" id="load_partial_tree">
    </div>
  </div>
</div>

app/views/server_main_infos/treeview_item.js.erb
$("#load_partial_tree").html("<%= escape_javascript( render partial: 'treeview', locals: { server_main_info: @treeviewItem} ) %>")