config/routes.rb
Rails.application.routes.draw do
  root 'mains#index'
  resources :users
  resources :roles
  resources :roles_names
  resources :mains
  resources :db_connections
  resources :applications
  resources :important_conf_files
  resources :partitionings
  resources :server_group_infos
  resources :server_states
  resources :os_infos
  resources :machine_types
  resources :site_names
  resources :ip_histories
  resources :server_main_infos do
    get 'treeview', on: :collection
    get 'treeview_item', on: :member
  end
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :server_main_info
  has_many :db_connections

end

app/models/db_connection.rb
class DbConnection < ApplicationRecord
  belongs_to :application
end

app/models/important_conf_file.rb
class ImportantConfFile < ApplicationRecord
end

app/models/ip_history.rb
class IpHistory < ApplicationRecord
  belongs_to :server_main_info

end

app/models/machine_type.rb
class MachineType < ApplicationRecord
  has_many :server_main_infos

end

app/models/os_info.rb
class OsInfo < ApplicationRecord
  has_many :server_main_infos

end

app/models/partitioning.rb
class Partitioning < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/roles_name.rb
class RolesName < ApplicationRecord
end

app/models/server_group_info.rb
class ServerGroupInfo < ApplicationRecord
  has_many :server_main_info

end

app/models/server_main_info.rb
require 'resolv'
class ServerMainInfo < ApplicationRecord
  belongs_to :os_info
  belongs_to :machine_type
  belongs_to :site_name
  belongs_to :server_state
  belongs_to :os_info
  has_many :ip_histories
  has_many :server_group_infos
  has_many :applications

  validates :srvName, :mainIP, :srvNameInProj, :srvPersianName, :sitename_id, :osinfo_id, :machinetype_id, :serverstate_id, :subnetMask, :gateWay,
            :projName, :responseName, :reponseUnit_id, :responseOrg_id, :responsePhone, presence: true
  validates :mainIP, :ip1, :ip2, :ip3, :validIP, :gateWay, format: { with: Resolv::IPv4::Regex , message: "آدرس شبکه ای دارای قالب درست نمی باشد" }
  validates :macAddr, :mac_1, :mac_2, :mac_3, format: { with: /\A([0-9a-fA-F]{2}:{1}){5}([0-9a-fA-F]{2}){1}\z/i , message: "قالب آدرس کارت شبکه صحیح نمی باشد"}
  validates :responseMail, format: { with: URI::MailTo::EMAIL_REGEXP, message: "قالب آدرس پست الکترونیکی صحیح نمی باشد"}
  validates :subnetMask, numericality: { only_integer: true, less_than_or_equal_to: 32 , greater_than_or_equal_to: 0}
  validates :fdqn, :validFqdn, format: { with: /\A\w+\.\w+\.\w\z/i , message: "لطفا نام شبکه ای را بطور صحیح وارد نمایید"}


end

app/models/server_state.rb
class ServerState < ApplicationRecord
  has_many :server_main_infos

end

app/models/site_name.rb
class SiteName < ApplicationRecord
  has_many :server_main_infos

end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/important_conf_files_controller.rb
class ImportantConfFilesController < ApplicationController
  before_action :set_important_conf_file, only: %i[ show edit update destroy ]

  # GET /important_conf_files or /important_conf_files.json
  def index
    @important_conf_files = ImportantConfFile.all
  end

  # GET /important_conf_files/1 or /important_conf_files/1.json
  def show
  end

  # GET /important_conf_files/new
  def new
    @important_conf_file = ImportantConfFile.new
  end

  # GET /important_conf_files/1/edit
  def edit
  end

  # POST /important_conf_files or /important_conf_files.json
  def create
    @important_conf_file = ImportantConfFile.new(important_conf_file_params)

    respond_to do |format|
      if @important_conf_file.save
        format.html { redirect_to @important_conf_file, notice: "Important conf file was successfully created." }
        format.json { render :show, status: :created, location: @important_conf_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @important_conf_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /important_conf_files/1 or /important_conf_files/1.json
  def update
    respond_to do |format|
      if @important_conf_file.update(important_conf_file_params)
        format.html { redirect_to @important_conf_file, notice: "Important conf file was successfully updated." }
        format.json { render :show, status: :ok, location: @important_conf_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @important_conf_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /important_conf_files/1 or /important_conf_files/1.json
  def destroy
    @important_conf_file.destroy
    respond_to do |format|
      format.html { redirect_to important_conf_files_url, notice: "Important conf file was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_important_conf_file
      @important_conf_file = ImportantConfFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def important_conf_file_params
      params.require(:important_conf_file).permit(:cfgFileName, :filePath, :servermaininfo_id, :note)
    end
end

app/helpers/important_conf_files_helper.rb
module ImportantConfFilesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/os_infos_helper.rb
module OsInfosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/site_names_helper.rb
module SiteNamesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/important_conf_files/_form.html.erb
<%= form_with(model: important_conf_file) do |form| %>
  <% if important_conf_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(important_conf_file.errors.count, "error") %> prohibited this important_conf_file from being saved:</h2>

      <ul>
        <% important_conf_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cfgFileName %>
    <%= form.text_field :cfgFileName %>
  </div>

  <div class="field">
    <%= form.label :filePath %>
    <%= form.text_field :filePath %>
  </div>

  <div class="field">
    <%= form.label :servermaininfo_id %>
    <%= form.number_field :servermaininfo_id %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/important_conf_files/edit.html.erb
<h1>Editing Important Conf File</h1>

<%= render 'form', important_conf_file: @important_conf_file %>

<%= link_to 'Show', @important_conf_file %> |
<%= link_to 'Back', important_conf_files_path %>

app/views/important_conf_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Important Conf Files</h1>

<table>
  <thead>
    <tr>
      <th><%= t :'activerecord.attributes.important_conf_file.cfgFileName' %></th>
      <th><%= t :'activerecord.attributes.important_conf_file.filePath' %></th>
      <th> Servermaininfo </th>
      <th><%= t :'activerecord.attributes.important_conf_file.note' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @important_conf_files.each do |important_conf_file| %>
      <tr>
        <td><%= important_conf_file.cfgFileName %></td>
        <td><%= important_conf_file.filePath %></td>
        <td><%= important_conf_file.servermaininfo_id %></td>
        <td><%= important_conf_file.note %></td>
        <td><%= link_to 'Show', important_conf_file %></td>
        <td><%= link_to 'Edit', edit_important_conf_file_path(important_conf_file) %></td>
        <td><%= link_to 'Destroy', important_conf_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Important Conf File', new_important_conf_file_path %>

app/views/important_conf_files/new.html.erb
<h1>New Important Conf File</h1>

<%= render 'form', important_conf_file: @important_conf_file %>

<%= link_to 'Back', important_conf_files_path %>

app/views/important_conf_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cfgfilename:</strong>
  <%= @important_conf_file.cfgFileName %>
</p>

<p>
  <strong>Filepath:</strong>
  <%= @important_conf_file.filePath %>
</p>

<p>
  <strong>Servermaininfo:</strong>
  <%= @important_conf_file.servermaininfo_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @important_conf_file.note %>
</p>

<%= link_to 'Edit', edit_important_conf_file_path(@important_conf_file) %> |
<%= link_to 'Back', important_conf_files_path %>