config/routes.rb
Rails.application.routes.draw do
  root 'mains#index'
  resources :users
  resources :roles
  resources :roles_names
  resources :mains
  resources :db_connections
  resources :applications
  resources :important_conf_files
  resources :partitionings
  resources :server_group_infos
  resources :server_states
  resources :os_infos
  resources :machine_types
  resources :site_names
  resources :ip_histories
  resources :server_main_infos do
    get 'treeview', on: :collection
    get 'treeview_item', on: :member
  end
  resources :tests
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :server_main_info
  has_many :db_connections

end

app/models/db_connection.rb
class DbConnection < ApplicationRecord
  belongs_to :application
end

app/models/ip_history.rb
class IpHistory < ApplicationRecord
  belongs_to :server_main_info

end

app/models/machine_type.rb
class MachineType < ApplicationRecord
  has_many :server_main_infos

end

app/models/os_info.rb
class OsInfo < ApplicationRecord
  has_many :server_main_infos

end

app/models/partitioning.rb
class Partitioning < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/roles_name.rb
class RolesName < ApplicationRecord
end

app/models/server_group_info.rb
class ServerGroupInfo < ApplicationRecord
  has_many :server_main_info

end

app/models/server_main_info.rb
require 'resolv'
class ServerMainInfo < ApplicationRecord
  belongs_to :os_info
  belongs_to :machine_type
  belongs_to :site_name
  belongs_to :server_state
  belongs_to :os_info
  has_many :ip_histories
  has_many :server_group_infos
  has_many :applications

  validates :srvName, :mainIP, :srvNameInProj, :srvPersianName, :sitename_id, :osinfo_id, :machinetype_id, :serverstate_id, :subnetMask, :gateWay,
            :projName, :responseName, :reponseUnit_id, :responseOrg_id, :responsePhone, presence: true
  validates :mainIP, :ip1, :ip2, :ip3, :validIP, :gateWay, format: { with: Resolv::IPv4::Regex , message: "آدرس شبکه ای دارای قالب درست نمی باشد" }
  validates :macAddr, :mac_1, :mac_2, :mac_3, format: { with: /\A([0-9a-fA-F]{2}:{1}){5}([0-9a-fA-F]{2}){1}\z/i , message: "قالب آدرس کارت شبکه صحیح نمی باشد"}
  validates :responseMail, format: { with: URI::MailTo::EMAIL_REGEXP, message: "قالب آدرس پست الکترونیکی صحیح نمی باشد"}
  validates :subnetMask, numericality: { only_integer: true, less_than_or_equal_to: 32 , greater_than_or_equal_to: 0}
  validates :fdqn, :validFqdn, format: { with: /\A\w+\.\w+\.\w\z/i , message: "لطفا نام شبکه ای را بطور صحیح وارد نمایید"}


end

app/models/server_state.rb
class ServerState < ApplicationRecord
  has_many :server_main_infos

end

app/models/site_name.rb
class SiteName < ApplicationRecord
  has_many :server_main_infos

end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/machine_types_controller.rb
class MachineTypesController < ApplicationController
  before_action :set_machine_type, only: %i[ show edit update destroy ]

  # GET /machine_types or /machine_types.json
  def index
    @machine_types = MachineType.all
  end

  # GET /machine_types/1 or /machine_types/1.json
  def show
  end

  # GET /machine_types/new
  def new
    @machine_type = MachineType.new
  end

  # GET /machine_types/1/edit
  def edit
  end

  # POST /machine_types or /machine_types.json
  def create
    @machine_type = MachineType.new(machine_type_params)

    respond_to do |format|
      if @machine_type.save
        format.html { redirect_to @machine_type, notice: "Machine type was successfully created." }
        format.json { render :show, status: :created, location: @machine_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @machine_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machine_types/1 or /machine_types/1.json
  def update
    respond_to do |format|
      if @machine_type.update(machine_type_params)
        format.html { redirect_to @machine_type, notice: "Machine type was successfully updated." }
        format.json { render :show, status: :ok, location: @machine_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @machine_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_types/1 or /machine_types/1.json
  def destroy
    @machine_type.destroy
    respond_to do |format|
      format.html { redirect_to machine_types_url, notice: "Machine type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine_type
      @machine_type = MachineType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_type_params
      params.require(:machine_type).permit(:machineType, :note)
    end
end

app/helpers/machine_types_helper.rb
module MachineTypesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/os_infos_helper.rb
module OsInfosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/site_names_helper.rb
module SiteNamesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/machine_types/_form.html.erb
<%= form_with(model: machine_type) do |form| %>
  <% if machine_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine_type.errors.count, "error") %> prohibited this machine_type from being saved:</h2>

      <ul>
        <% machine_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :machineType %>
    <%= form.text_field :machineType %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machine_types/edit.html.erb
<h1>Editing Machine Type</h1>

<%= render 'form', machine_type: @machine_type %>

<%= link_to 'Show', @machine_type %> |
<%= link_to 'Back', machine_types_path %>

app/views/machine_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machine Types</h1>

<table>
  <thead>
    <tr>
      <th>Machinetype</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machine_types.each do |machine_type| %>
      <tr>
        <td><%= machine_type.machineType %></td>
        <td><%= machine_type.note %></td>
        <td><%= link_to 'Show', machine_type %></td>
        <td><%= link_to 'Edit', edit_machine_type_path(machine_type) %></td>
        <td><%= link_to 'Destroy', machine_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine Type', new_machine_type_path %>

app/views/machine_types/new.html.erb
<h1>New Machine Type</h1>

<%= render 'form', machine_type: @machine_type %>

<%= link_to 'Back', machine_types_path %>

app/views/machine_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Machinetype:</strong>
  <%= @machine_type.machineType %>
</p>

<p>
  <strong>Note:</strong>
  <%= @machine_type.note %>
</p>

<%= link_to 'Edit', edit_machine_type_path(@machine_type) %> |
<%= link_to 'Back', machine_types_path %>